### ISSUE TITLE
Main project sample errors!

### ISSUE THREAD

**Issue by agh620** [SjoerdTilmans/sjvisualizer#28]
When I run your project samples in jupyter notebook I get following errors:  
in "# adding the bar race to the canvas" cell:  
````
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_2784\3923102217.py in ?()
      1 # adding the bar race to the canvas
----> 2 canvas.add_sub_plot(bar_race)

~\AppData\Local\Programs\Python\Python311\Lib\site-packages\sjvisualizer\Canvas.py in ?(self, sub_plot)
    120 
    121         :param sub_plot: sub_plot object
    122         :type sub_plot: sjvisualizer.Canvas.sub_plot
    123         """
--> 124         sub_plot.set_root(self.tk)
    125         self.sub_canvas.append(sub_plot)

~\AppData\Local\Programs\Python\Python311\Lib\site-packages\sjvisualizer\Canvas.py in ?(self, root)
    338     def set_root(self, root):
    339         if not self.root:
    340             self.root = root
--> 341             self.draw(self.start_time)

~\AppData\Local\Programs\Python\Python311\Lib\site-packages\sjvisualizer\BarRace.py in ?(self, time)
    166         self.stripes = bar_stripes(self.canvas, self.y_pos, self.y_pos + self.height, data, self.x_pos + self.width/5, self.width*0.75, self.height, self.number_of_bars, self.invert, allow_decrease=self.allow_decrease)
    167 
    168         current_height = self.distance/2 + self.y_pos
    169         bar_number = 0
--> 170         for i, (name, value) in enumerate(data.data.iteritems()):
    171             if not self.invert:
    172                 fraction = value / data.max()
    173                 self.current_max = data.max()

~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\generic.py in ?(self, name)
   5985             and name not in self._accessors
   5986             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987         ):
   5988             return self[name]
-> 5989         return object.__getattribute__(self, name)

AttributeError: 'Series' object has no attribute 'data'
````  
  
  
   
   
   
   
   
   
   
in "canvas.play(fps=FPS)" cell:  
````
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[9], line 1
----> 1 canvas.play(fps=FPS)

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\sjvisualizer\Canvas.py:147, in canvas.play(self, df, fps)
    144         if not sub.df is None:
    145             df = sub.df
--> 147 for i, date_time in enumerate(df.index):
    148     start = time.time()
    150     self.update(date_time)

AttributeError: 'NoneType' object has no attribute 'index'
````  
  
  
  
   
   
   
   
If it possible respond me very soon!

**Comment by agh620** [comment]
> When I run your project samples in jupyter notebook I get following errors: in "# adding the bar race to the canvas" cell:
> 
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> ~\AppData\Local\Temp\ipykernel_2784\3923102217.py in ?()
>       1 # adding the bar race to the canvas
> ----> 2 canvas.add_sub_plot(bar_race)
> 
> ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\sjvisualizer\Canvas.py in ?(self, sub_plot)
>     120 
>     121         :param sub_plot: sub_plot object
>     122         :type sub_plot: sjvisualizer.Canvas.sub_plot
>     123         """
> --> 124         sub_plot.set_root(self.tk)
>     125         self.sub_canvas.append(sub_plot)
> 
> ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\sjvisualizer\Canvas.py in ?(self, root)
>     338     def set_root(self, root):
>     339         if not self.root:
>     340             self.root = root
> --> 341             self.draw(self.start_time)
> 
> ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\sjvisualizer\BarRace.py in ?(self, time)
>     166         self.stripes = bar_stripes(self.canvas, self.y_pos, self.y_pos + self.height, data, self.x_pos + self.width/5, self.width*0.75, self.height, self.number_of_bars, self.invert, allow_decrease=self.allow_decrease)
>     167 
>     168         current_height = self.distance/2 + self.y_pos
>     169         bar_number = 0
> --> 170         for i, (name, value) in enumerate(data.data.iteritems()):
>     171             if not self.invert:
>     172                 fraction = value / data.max()
>     173                 self.current_max = data.max()
> 
> ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\generic.py in ?(self, name)
>    5985             and name not in self._accessors
>    5986             and self._info_axis._can_hold_identifiers_and_holds_name(name)
>    5987         ):
>    5988             return self[name]
> -> 5989         return object.__getattribute__(self, name)
> 
> AttributeError: 'Series' object has no attribute 'data'
> ```
> 
> in "canvas.play(fps=FPS)" cell:
> 
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[9], line 1
> ----> 1 canvas.play(fps=FPS)
> 
> File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\sjvisualizer\Canvas.py:147, in canvas.play(self, df, fps)
>     144         if not sub.df is None:
>     145             df = sub.df
> --> 147 for i, date_time in enumerate(df.index):
>     148     start = time.time()
>     150     self.update(date_time)
> 
> AttributeError: 'NoneType' object has no attribute 'index'
> ```
> 
> If it possible respond me very soon!

**Comment by SjoerdTilmans** [comment]
Thanks for closing this already. Looking at the error it looks like there is something wrong with your data file. The most important thing is that Excel recognises the cell value as a date.
