### ISSUE TITLE
How to change dates from years to years quarter or years months?

### ISSUE THREAD

**Issue by agh620** [SjoerdTilmans/sjvisualizer#29]
in this project I can only show dates as years  
Now I need to use "Years Quarters" or "Years Months" like following:  
2001 Q1
2001 Q2
2001 Q3
2001 Q4

2001 Jul
2001 Jun
2002 Sep
2002 Aug

How can I change type of dates in sjvisualizer?

**Comment by SjoerdTilmans** [comment]
The most important thing would be to ensure that Excel recognises the cell as a date. If you want to use quarterly data or monthly data I would recommend converting that to an actual date, for example 2001 Q1 would be come 1-1-2001.

Hope this helps.

**Comment by agh620** [comment]
> The most important thing would be to ensure that Excel recognises the cell as a date. If you want to use quarterly data or monthly data I would recommend converting that to an actual date, for example 2001 Q1 would be come 1-1-2001.
> 
> Hope this helps.

tnq it working good but it output chart only years appearance - no any quarter or month appearance

**Comment by SjoerdTilmans** [comment]
Quarters can't be displayed today. But months can. When you construct the linechart object, there is an optional argument time_indicator. This can be set to "day", "month" or "year".


From the docstrings:
      :param time_indicator: format of the timestamp, "day", "month", "year", default is "year"
      :type time_indicator: str

**Comment by agh620** [comment]
If it possible add quarter to project too

**Comment by SjoerdTilmans** [comment]
Not today, but the code is open-source, so you can extend it if you want to. Otherwise raise an issue.
