### ISSUE TITLE
How to play created bar chart in android phone?

### ISSUE THREAD

**Issue by agh620** [SjoerdTilmans/sjvisualizer#31]
I want to play my created bar chart race in my android phone and record video from it because recording video from my mobile screen have very better quality.  
how can I do this?
is there any way to move and play created sjvisualizer bar chart in my android phone?

**Comment by agh620** [comment]
if it possible please help for this problem soon

**Comment by SjoerdTilmans** [comment]
This is not possible. The code is written in python which is not supported on Android. The only option is to record on your computer and move the video to your phone.
